import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import 'swiper/css/bundle'
import HomeLayout from '../components/Layouts'
import Navbar from '../components/Nav/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
        <div className=' w-full  '>
          <Hero />
        </div>
      </HomeLayout>
    </div>
  )
}
