import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Nav/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='border-b w-full'>
        <Navbar />
      </div>
    </div>
  )
}
